# Generated by Django 5.1.3 on 2024-12-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_merge_20241212_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdiaryboard',
            name='nicName',
        ),
    ]
