# Generated by Django 5.1.3 on 2024-12-13 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_remove_diaryboard_like_members'),
        ('diary', '0011_remove_mdiaryboard_nicname'),
    ]

    operations = [
    ]
