# Generated by Django 5.1.3 on 2024-12-11 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionscore',
            name='diaryNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotionscore',
            name='diarydate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
