# Generated by Django 5.1.3 on 2024-12-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_alter_member_nicname'),
        ('loginpage', '0003_member_created_group_member_joined_group'),
    ]

    operations = [
    ]
