# Generated by Django 5.1.3 on 2024-12-10 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginpage', '0003_alter_member_nicname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(default='장소가 없습니다.', max_length=255)),
                ('repeat', models.CharField(default='none', max_length=10)),
                ('memo', models.TextField(default='내용이없습니다.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginpage.member')),
            ],
        ),
    ]
