# Generated by Django 5.1.3 on 2024-12-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='제목이없습니다.', max_length=255, null=True),
        ),
    ]
