# Generated by Django 5.1.3 on 2024-12-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar1', '0002_alter_event_end_date_alter_event_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#0000FF', max_length=7),
        ),
    ]
