# Generated by Django 5.1.3 on 2024-12-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar1', '0003_event_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='#0000FF', max_length=20),
        ),
    ]
