# Generated by Django 5.1.3 on 2024-12-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar1', '0004_alter_event_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat',
            field=models.CharField(choices=[('none', '없음'), ('daily', '매일'), ('weekly', '매주'), ('monthly', '매월'), ('yearly', '매년')], default='none', max_length=20),
        ),
    ]
