# Generated by Django 5.1.3 on 2024-12-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar1', '0005_alter_event_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='#0000FF', max_length=100),
        ),
    ]
